version: '3'
services:
  portfolio-web:
      container_name: portfolio-web
      image: nginx:1.13
      restart: always
      environment:
        VIRTUAL_HOST: ${VIRTUAL_HOST}
        LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
        LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
        SETREALIPFROM: ${SETREALIPFROM}
      volumes:
        - ./nginx/conf:/etc/nginx/conf.d
        - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
        - ./src/static:/static
        - ./src/media:/media
      command: /bin/sh -c "envsubst '$$SETREALIPFROM' < /etc/nginx/conf.d/portfolio.conf.template > /etc/nginx/conf.d/portfolio.conf && nginx -g 'daemon off;'"
      depends_on:
        - portfolio-app
      networks:
        - proxy-network
        - portfolio-app-network

  portfolio-db:
      container_name: portfolio-db
      image: mysql:5.7
      restart: always
      expose:
        - "3306"
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_USER_HOST: ${MYSQL_USER_HOST}
        REPLICATION_USER: ${REPLICATION_USER}
        REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
        REPLICATION_HOST: ${REPLICATION_HOST}
        TZ: 'Asia/Tokyo'
      volumes:
        - portfolio-db:/var/lib/mysql
        - ./mysql/sql:/docker-entrypoint-initdb.d
        - ./mysql/conf:/etc/mysql/conf.d/
      networks:
        - portfolio-db-network

  portfolio-app:
      container_name: portfolio-app
      build: ./django
      restart: always
      command: >
        bash -c
        "./portfolio/fixtures/init/wait-for-it.sh portfolio-db:3306
        && python manage.py makemigrations
        && python manage.py migrate
        && python manage.py custom_createsuperuser
        --username ${ADMIN_USER}
        --email ${ADMIN_EMAIL}
        --password ${ADMIN_PASSWORD}
        && uwsgi --ini /code/uwsgi.ini"
      volumes:
        - ./src:/code
        - ./src/static:/static
        - ./.env:/code/mysite/.env
      expose:
        - "8001"
      depends_on:
        - portfolio-db
      networks:
        - portfolio-app-network
        - portfolio-db-network
networks:
  portfolio-app-network:
    external: true
  proxy-network:
    external: true
  portfolio-db-network:
    external: true
volumes:
  portfolio-db:
    driver: local