# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(max_length=300)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_product_name', models.CharField(default='', max_length=20, unique=True)),
                ('engineer_product_alphabet_name', models.CharField(default='', max_length=40, unique=True)),
                ('engineer_product_short_concept', models.CharField(default='', max_length=30)),
                ('top_image', models.ImageField(blank=True, upload_to=portfolio.models.EngineerProduct.get_top_file_name)),
                ('col1_image', models.ImageField(blank=True, upload_to=portfolio.models.EngineerProduct.get_col1_file_name)),
                ('col2_image', models.ImageField(blank=True, upload_to=portfolio.models.EngineerProduct.get_col2_file_name)),
                ('col3_image', models.ImageField(blank=True, upload_to=portfolio.models.EngineerProduct.get_col3_file_name)),
                ('link', models.URLField(blank=True, default='')),
                ('votes', models.IntegerField(default=0)),
                ('sort_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_product_feature_concept', models.TextField(blank=True, default='', max_length=30)),
                ('engineer_product_feature_detail', models.TextField(blank=True, default='', max_length=300)),
                ('engineer_product_background_concept', models.TextField(blank=True, default='', max_length=30)),
                ('engineer_product_background_detail', models.TextField(blank=True, default='', max_length=300)),
                ('engineer_product_development_environment', models.TextField(blank=True, default='', max_length=300)),
                ('engineer_product_development_language', models.TextField(blank=True, default='', max_length=300)),
                ('engineer_product_creation_time', models.TextField(blank=True, default='', max_length=50)),
                ('engineer_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.EngineerProduct')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer_product_location', models.CharField(blank=True, default='', max_length=30)),
                ('photographer_product_shooting_year', models.CharField(blank=True, default='', max_length=4)),
                ('photographer_product_shooting_month', models.CharField(blank=True, default='', max_length=2)),
                ('photographer_product_shooting_hour', models.CharField(blank=True, default='', max_length=2)),
                ('photographer_product_shooting_minute', models.CharField(blank=True, default='', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.EngineerProduct'),
        ),
    ]
