# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_function_concept',
            new_name='product_feature_concept',
        ),
        migrations.RenameField(
            model_name='productdetail',
            old_name='product_function_detail',
            new_name='product_feature_detail',
        ),
    ]
