# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170322_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerproduct',
            name='photographer_product_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
