# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20170318_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='title',
        ),
        migrations.AddField(
            model_name='imagefile',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.Product'),
        ),
    ]
