# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170318_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefile',
            name='title',
            field=models.CharField(choices=[('S1', '画像1'), ('S2', '画像2'), ('S3', '画像3')], default='S1', max_length=2),
        ),
    ]
