# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20170222_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='data',
            field=models.ImageField(upload_to='images'),
        ),
    ]
