# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_imagefile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.ImageFile.content_file_name),
        ),
    ]
