# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170318_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='title',
            field=models.CharField(choices=[('S1', 'img1'), ('S2', 'img2'), ('S3', 'img3')], default='S1', max_length=2),
        ),
    ]
