# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20170222_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
