# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170324_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographerproduct',
            name='photographer_product_shooting_year',
            field=models.IntegerField(blank=True, default=2000),
        ),
    ]
