# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_imagefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='/Users/Kenta/PycharmProjects/mysite/media')),
                ('externalURL', models.URLField(blank=True)),
            ],
        ),
    ]
