# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20170318_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_alphabet_name',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='product',
            name='top_image',
            field=models.ImageField(blank=True, upload_to=portfolio.models.Product.content_file_name),
        ),
    ]
