# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagefile',
            name='externalURL',
        ),
        migrations.RemoveField(
            model_name='imagefile',
            name='title',
        ),
    ]
