# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20170324_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineerproduct',
            name='sort_id',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='photographerproduct',
            name='sort_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
