# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20170222_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
