# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_product_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_development_environment',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='productdetail',
            name='product_development_language',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_background_concept',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_background_detail',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_feature_concept',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_feature_detail',
            field=models.TextField(default='', max_length=300),
        ),
    ]
