# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_imagefile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_short_concept',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='top_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
