# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-28 12:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20170326_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerproduct',
            name='votes',
        ),
    ]
