# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_remove_engineerproduct_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='', max_length=300),
        ),
    ]
