# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_auto_20170316_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default='', verbose_name='date published'),
        ),
    ]
