# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20170320_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_background_concept',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_feature_concept',
            field=models.TextField(default='', max_length=30),
        ),
    ]
