# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_product_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 16, 3, 39, 27, 788602), verbose_name='date published'),
        ),
    ]
