# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20170320_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_short_concept',
            field=models.CharField(default='', max_length=30),
        ),
    ]
