# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20170331_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(blank=True, default='名無し', max_length=50),
        ),
    ]
