# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20170320_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sort_id',
            field=models.IntegerField(default=0),
        ),
    ]
