# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-01-09 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20170401_0616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='link',
            new_name='github',
        ),
        migrations.AddField(
            model_name='engineerproduct',
            name='store',
            field=models.URLField(blank=True, default=''),
        ),
    ]
