# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_product_sort_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_background_concept',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_background_detail',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_creation_time',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_development_environment',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_development_language',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_feature_concept',
            field=models.TextField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_feature_detail',
            field=models.TextField(blank=True, default='', max_length=300),
        ),
    ]
