# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20170316_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2017, 3, 16), null=True, verbose_name='date published'),
        ),
    ]
