# Generated by Django 2.1.1 on 2018-09-25 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20180925_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerproductdetail',
            name='engineer_product',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_alphabet_name',
            new_name='alphabet_name',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_background_concept',
            new_name='background_concept',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_background_detail',
            new_name='background_detail',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_creation_time',
            new_name='creation_time',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_development_environment',
            new_name='development_environment',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_development_language',
            new_name='development_language',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_feature_concept',
            new_name='feature_concept',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_feature_detail',
            new_name='feature_detail',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='engineerproduct',
            old_name='engineer_product_short_concept',
            new_name='short_concept',
        ),
        migrations.DeleteModel(
            name='EngineerProductDetail',
        ),
    ]
