# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20170322_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_alphabet_name',
            field=models.CharField(default='', max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
