# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_remove_product_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.date(2017, 3, 16), verbose_name='date published'),
        ),
    ]
