# Generated by Django 2.1.1 on 2018-09-25 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20180925_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_alphabet_name',
            new_name='alphabet_name',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_main_image',
            new_name='main_image',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_shooting_day',
            new_name='shooting_day',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_shooting_hour',
            new_name='shooting_hour',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_shooting_minute',
            new_name='shooting_minute',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_shooting_month',
            new_name='shooting_month',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_product_shooting_year',
            new_name='shooting_year',
        ),
        migrations.RenameField(
            model_name='photographerproduct',
            old_name='photographer_thumbnail_image',
            new_name='thumbnail_image',
        ),
    ]
