# Generated by Django 2.1.1 on 2018-09-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20180925_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographerproduct',
            name='shooting_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
