# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20170322_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_location',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='product_shooting_date_month',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='product_shooting_date_year',
            field=models.CharField(blank=True, default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='sort_id',
            field=models.IntegerField(default=0),
        ),
    ]
