# Generated by Django 2.1.1 on 2018-09-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20180925_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photographerproduct',
            name='shooting_day',
        ),
        migrations.RemoveField(
            model_name='photographerproduct',
            name='shooting_hour',
        ),
        migrations.RemoveField(
            model_name='photographerproduct',
            name='shooting_minute',
        ),
        migrations.RemoveField(
            model_name='photographerproduct',
            name='shooting_month',
        ),
        migrations.RemoveField(
            model_name='photographerproduct',
            name='shooting_year',
        ),
    ]
