# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 18:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20170316_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 18, 55, 54, 76456, tzinfo=utc), verbose_name='date published'),
        ),
    ]
