# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20170316_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 15, 19, 2, 9, 780979, tzinfo=utc)),
        ),
    ]
