# Generated by Django 2.1.1 on 2018-09-27 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
