# Generated by Django 2.1.1 on 2018-09-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20180927_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
