# Generated by Django 2.1.1 on 2018-09-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_privacypolicy_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privacypolicy',
            unique_together={('sort_id', 'engineer_product')},
        ),
    ]
