# Generated by Django 2.1.1 on 2018-09-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_auto_20180927_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacypolicy',
            name='sort_id',
            field=models.IntegerField(default=0),
        ),
    ]
